# Generated by Django 3.1.5 on 2021-01-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desired_price_on_site',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='site_name',
        ),
    ]
