# Generated by Django 3.1.5 on 2021-01-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricetracker', '0002_auto_20210126_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desired_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailaddress',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
