# Generated by Django 3.1.5 on 2021-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricetracker', '0003_auto_20210127_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desired_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available_at_desired_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='last_checked_price',
            field=models.FloatField(default=0),
        ),
    ]
