# Generated by Django 3.1.5 on 2021-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricetracker', '0004_auto_20210128_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site_title',
            field=models.CharField(default='site_name', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_checked_price',
            field=models.FloatField(default=1.7976931348623157e+308),
        ),
    ]
